apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: axonserver
  labels:
    app: axonserver
spec:
  serviceName: axonserver
  replicas: 1
  selector:
    matchLabels:
      app: axonserver
  template:
    metadata:
      labels:
        app: axonserver
    spec:
      containers:
        - name: axonserver
          image: axoniq/axonserver
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 8124
              protocol: TCP
            - name: http
              containerPort: 8024
              protocol: TCP
          volumeMounts:
            - name: eventstore
              mountPath: /eventdata
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              port: http
              path: /actuator/info
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              port: gui
              path: /actuator/info
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 1
          resources:
            requests:
              memory: "4Gi"  # Imposta la quantità di memoria richiesta a 4 gigabyte
              cpu: "1"       # Imposta la quantità di CPU richiesta a 1 core
            limits:
              memory: "8Gi"  # Imposta il limite di memoria a 8 gigabyte (opzionale)
              cpu: "2"       # Imposta il limite di CPU a 2 core (opzionale)
  volumeClaimTemplates:
    - metadata:
        name: eventstore
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi


---
apiVersion: v1
kind: Service
metadata:
  name: axonserver-gui
  labels:
    app: axonserver
spec:
  ports:
    - name: gui
      port: 8024
      targetPort: 8024
      nodePort: 30002
  selector:
    app: axonserver
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: axonserver-grpc
  labels:
    app: axonserver
spec:
  ports:
    - name: grpc
      port: 8124
      targetPort: 8124
  clusterIP: None
  selector:
    app: axonserver