apiVersion: apps/v1
kind: Deployment
metadata:
  name: box-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: box-service
  template:
    metadata:
      labels:
        app: box-service
    spec:
      containers:
        - name: box-service
          image: tommimassa98/savefood-box-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: eureka.client.serviceUrl.defaultZone
              value: http://discovery-server:8761/eureka
            - name: axon.axonserver.servers
              value: axonserver-grpc:8124
---

apiVersion: v1
kind: Service
metadata:
  name: box-service
spec:
  selector:
    app: box-service
  ports:
    - port: 8081
      targetPort: 8081