apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: tommimassa98/savefood-discovery-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: eureka.instance.hostname
              value: discovery-server
            - name: eureka.client.serviceUrl.defaultZone
              value: http://discovery-server:8761/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30001
  type: LoadBalancer