# Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-reservation-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-reservation
  template:
    metadata:
      labels:
        app: postgres-reservation
    spec:
      containers:
        - name: postgres-reservation
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: reservation-db
            - name: POSTGRES_USER
              value: ted
            - name: POSTGRES_PASSWORD
              value: qazmlpD
          volumeMounts:
            - name: reservation-db-data
              mountPath: /data/postgres
      volumes:
        - name: reservation-db-data
          persistentVolumeClaim:
            claimName: postgres-reservation-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-reservation
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-reservation