apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: tommimassa98/savefood-review-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: eureka.client.serviceUrl.defaultZone
              value: http://discovery-server:8761/eureka
            - name: axon.axonserver.servers
              value: axonserver-grpc:8124
---

apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  selector:
    app: review-service
  ports:
    - port: 8085
      targetPort: 8085